
const imageSets = [
    [
        'img/casa1/1.jpg',
        'img/casa1/2.jpg',
        'img/casa1/3.jpg',
        'img/casa1/4.jpg',
        'img/casa1/5.jpg',
        'img/casa1/6.jpg',
        'img/casa1/7.jpg',
        'img/casa1/8.jpg',
        'img/casa1/9.jpg',
        'img/casa1/10.jpg',
        'img/casa1/11.jpg',
        'img/casa1/12.jpg'
        
    ],
    [
        'img/casa2/1.jpg',
        'img/casa2/2.jpg',
        'img/casa2/3.jpg',
        'img/casa2/4.jpg',
        'img/casa2/5.jpg',
        'img/casa2/6.jpg',
        'img/casa2/7.jpg',
        'img/casa2/8.jpg',
        'img/casa2/9.jpg',
        'img/casa2/10.jpg',
        'img/casa2/11.jpg',
        'img/casa2/12.jpg',
        'img/casa2/13.jpg',
        'img/casa2/14.jpg',
        'img/casa2/15.jpg',
        'img/casa2/16.jpg',
        'img/casa4/1.jpg',
        'img/casa4/2.jpg',
        'img/casa4/3.jpg',
        'img/casa4/4.jpg',
        'img/casa4/5.jpg',
        'img/casa4/6.jpg',
        'img/casa4/7.jpg',
        'img/casa4/8.jpg',
        'img/casa4/9.jpg',
        'img/casa4/10.jpg',
        'img/casa4/11.jpg',
        'img/casa4/12.jpg'
    ],
    [
        'img/casa3/1.jpg',
        'img/casa3/2.jpg',
        'img/casa3/3.jpg',
        'img/casa3/4.jpg',
        'img/casa3/5.jpg',
        'img/casa3/6.jpg',
        'img/casa3/7.jpg',
        'img/casa3/8.jpg',
        'img/casa3/9.jpg',
        'img/casa3/10.jpg',
        'img/casa3/11.jpg',
        'img/casa3/12.jpg',
        'img/casa3/13.jpg',
        'img/casa3/14.jpg'
    
    ],
   
    [
        'img/casa5/1.jpg',
        'img/casa5/2.jpg',
        'img/casa5/3.jpg',
        'img/casa5/4.jpg',
        'img/casa5/5.jpg',
        'img/casa5/6.jpg',
        'img/casa5/7.jpg',
        'img/casa5/8.jpg',
        'img/casa5/9.jpg',
        'img/casa5/10.jpg',
        'img/casa5/11.jpg',
        'img/casa5/12.jpg',
        'img/casa5/13.jpg',
        'img/casa5/14.jpg'
        
    ]
];
