
const imageSets = [
    [
        '../img/img teste/1.jpg',
        '../img/img teste/2.jpg',
        '../img/img teste/3.jpg',
        '../img/img teste/4.jpg',
        '../img/img teste/5.jpg',
        '../img/img teste/15.jpg',
        '../img/img teste/17.jpg',
        '../img/img teste/13.jpg',
        '../img/img teste/6.jpg',
        '../img/img teste/7.jpg',
        '../img/img teste/8.jpg',
        '../img/img teste/9.jpg',
        '../img/img teste/10.jpg',
        '../img/img teste/11.jpg',
        '../img/img teste/11.jpg',
        '../img/img teste/12.jpg'
    ],
    [
        '../img/img teste/4.jpg',
        '../img/img teste/6.jpg',
        '../img/img teste/7.jpg',
        '../img/img teste/11.jpg',
        '../img/img teste/17.jpg',
        '../img/img teste/18.jpg',
        '../img/img teste/2.jpg',
        '../img/img teste/1.jpg',
    ],
    [
        '../img/img teste/1.jpg',
        '../img/img teste/2.jpg',
        '../img/img teste/3.jpg',
        '../img/img teste/4.jpg',
        '../img/img teste/5.jpg',
        '../img/img teste/15.jpg',
        '../img/img teste/17.jpg',
        '../img/img teste/15.jpg',
    ],
    [
        '../img/img teste/1.jpg',
        '../img/img teste/2.jpg',
        '../img/img teste/3.jpg',
        '../img/img teste/4.jpg',
        '../img/img teste/5.jpg',
        '../img/img teste/15.jpg',
        '../img/img teste/17.jpg',
        '../img/img teste/15.jpg',
        '../img/img teste/4.jpg',
        '../img/img teste/6.jpg',
        '../img/img teste/7.jpg',
        '../img/img teste/11.jpg',
        '../img/img teste/17.jpg',
        '../img/img teste/18.jpg',
        '../img/img teste/2.jpg',
        '../img/img teste/1.jpg'
    ],
    [
       '../img/img teste/1.jpg',
        '../img/img teste/2.jpg',
        '../img/img teste/3.jpg',
        '../img/img teste/4.jpg',
        
    ]
];
